Include tests for Rx, Ry, Rz, U2, U3, Hz & FSim
bsc-quantic/Quac.jl pull request #47
Opened 2024-03-08 17:15 UTC by Todorbsc

Closes #35

2024-03-08 17:26 UTC, Todorbsc commented
Just to verify, I would like you to review the definition of the `Hz` and `FSim` and compare it to the ones defined in Cirq. Probably, you did some equivalence as the one @mofeing told me about the RZ gate.

![image](https://github.com/bsc-quantic/Quac.jl/assets/145352308/b9e638ab-9c1b-4923-823e-59ac8cf600ac)

Cirq Hz:
![image](https://github.com/bsc-quantic/Quac.jl/assets/145352308/42ae84d3-6809-442a-a254-d472468c99e0)

Cirq FSim:
![image](https://github.com/bsc-quantic/Quac.jl/assets/145352308/03d6d1dd-2888-49be-9d10-30f1a0feb2a3)

2024-03-08 17:52 UTC, mofeing approved these changes
Great thanks! I will revise `FSim` and `Hz` now.

2024-03-08 17:52 UTC, mofeing commented on test/Array_test.jl
> +        end
You forgot to add a newline here.
```suggestion
        end

```

2024-03-08 17:54 UTC, jofrevalles requested changes

2024-03-08 17:54 UTC, jofrevalles commented on test/Array_test.jl
> +
```suggestion
```

Remove this empty line

2024-03-08 17:54 UTC, jofrevalles approved these changes

2024-03-08 17:58 UTC, mofeing commented
The `Hz` gate seems correct. Check out that `cis(x) = exp(1im * x)`.
But `FSim` seems to be wrong... would you mind fixing it?

2024-03-11 10:51 UTC, Todorbsc commented
> The `Hz` gate seems correct. Check out that `cis(x) = exp(1im * x)`. But `FSim` seems to be wrong... would you mind fixing it?

I fixed `FSim` according to the Cirq definition of the gate. Check it out.
Regarding the `Hz` gate, there is an opposite phase in the off-diagonal with respect to the Cirq definition while the diagonal is the same.

Cirq:
![image](https://github.com/bsc-quantic/Quac.jl/assets/145352308/eca7e9ec-e250-4b49-97b0-511448634fd7)

Our definition:
$$ \begin{bmatrix}
e^{i \theta / 2} cos(\theta / 2) & -i e^{-i (\theta / 2 - \phi)} sin(\theta / 2) \\
-i e^{-i (\theta / 2 + \phi)} sin(\theta / 2) & e^{i \theta / 2} cos(\theta / 2) \\
\end{bmatrix}, \theta = \pi t , \phi = \pi t$$

If this is not a problem, we can merge the PR.

2024-03-11 11:29 UTC, mofeing approved these changes
Great! Thanks!

2024-03-11 11:31 UTC, merged